from building import *

cwd     = GetCurrentDir()
src     = ['dfs_littlefs_pico.c']
CPPPATH = [cwd]

group = DefineGroup('Filesystem', src, depend = ['RT_USING_DFS', 'RT_USING_DFS_LITTLEFS'], CPPPATH = CPPPATH)

Return('group')
